import os
import smtplib
import textwrap
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def send_summary_email(recipient: str, summary: str, filename: str) -> None:
    """Send a formatted HTML email with the AI-generated sales summary."""
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER")
    smtp_password = os.getenv("SMTP_PASSWORD")
    sender_name = os.getenv("SENDER_NAME", "Rabbitt AI — Sales Insights")

    if not smtp_user or not smtp_password:
        raise RuntimeError("SMTP credentials are not configured.")

    # Convert markdown-ish summary to HTML paragraphs
    html_body = _to_html(summary)

    html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Sales Insight Report</title>
</head>
<body style="margin:0;padding:0;background:#0f1117;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0f1117;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="620" cellpadding="0" cellspacing="0"
               style="background:linear-gradient(135deg,#1a1d2e 0%,#16192a 100%);
                      border-radius:16px;border:1px solid rgba(139,92,246,0.3);
                      overflow:hidden;max-width:620px;">
          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#7c3aed,#4f46e5);
                       padding:32px 40px;text-align:center;">
              <div style="font-size:28px;font-weight:700;color:#fff;letter-spacing:-0.5px;">
                🐇 Rabbitt AI
              </div>
              <div style="font-size:14px;color:rgba(255,255,255,0.75);margin-top:4px;letter-spacing:2px;text-transform:uppercase;">
                Sales Intelligence Platform
              </div>
            </td>
          </tr>
          <!-- Subtitle bar -->
          <tr>
            <td style="background:rgba(139,92,246,0.15);padding:14px 40px;border-bottom:1px solid rgba(139,92,246,0.2);">
              <span style="color:#a78bfa;font-size:13px;font-weight:600;text-transform:uppercase;letter-spacing:1.5px;">
                📊 AI Executive Summary — Q1 2026
              </span>
            </td>
          </tr>
          <!-- File badge -->
          <tr>
            <td style="padding:24px 40px 0;">
              <div style="display:inline-block;background:rgba(79,70,229,0.2);
                          border:1px solid rgba(79,70,229,0.4);border-radius:8px;
                          padding:8px 16px;font-size:13px;color:#818cf8;">
                📁 Source file: <strong style="color:#a5b4fc;">{filename}</strong>
              </div>
            </td>
          </tr>
          <!-- Summary content -->
          <tr>
            <td style="padding:24px 40px 32px;">
              <div style="color:#e2e8f0;font-size:15px;line-height:1.8;">
                {html_body}
              </div>
            </td>
          </tr>
          <!-- Divider -->
          <tr>
            <td style="padding:0 40px;">
              <div style="height:1px;background:linear-gradient(90deg,transparent,rgba(139,92,246,0.4),transparent);"></div>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="padding:24px 40px;text-align:center;">
              <p style="color:#475569;font-size:12px;margin:0;">
                This report was auto-generated by <strong style="color:#7c3aed;">Rabbitt AI Sales Insight Automator</strong>
                powered by <strong style="color:#7c3aed;">Groq · Llama 3</strong>.
                <br/>Please do not reply to this email.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"📊 Sales Insight Report — {filename}"
    msg["From"] = f"{sender_name} <{smtp_user}>"
    msg["To"] = recipient

    # Plain text fallback
    plain = textwrap.dedent(f"""
    RABBITT AI — SALES INSIGHT REPORT
    Source file: {filename}
    ────────────────────────────────────

    {summary}

    ────────────────────────────────────
    Auto-generated by Rabbitt AI Sales Insight Automator (Groq · Llama 3)
    """).strip()

    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html_content, "html"))

    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.ehlo()
        server.starttls()
        server.login(smtp_user, smtp_password)
        server.sendmail(smtp_user, recipient, msg.as_string())


def _to_html(text: str) -> str:
    """Convert simple markdown-ish text to basic HTML."""
    lines = text.split("\n")
    html_lines = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            html_lines.append("<br/>")
        elif stripped.startswith("## "):
            html_lines.append(
                f'<h2 style="color:#a78bfa;font-size:17px;font-weight:700;'
                f'margin:20px 0 8px;border-bottom:1px solid rgba(167,139,250,0.3);'
                f'padding-bottom:6px;">{stripped[3:]}</h2>'
            )
        elif stripped.startswith("# "):
            html_lines.append(
                f'<h1 style="color:#c4b5fd;font-size:20px;font-weight:700;'
                f'margin:24px 0 12px;">{stripped[2:]}</h1>'
            )
        elif stripped.startswith("- ") or stripped.startswith("* "):
            html_lines.append(
                f'<li style="margin:6px 0;color:#cbd5e1;">{stripped[2:]}</li>'
            )
        elif stripped.startswith("**") and stripped.endswith("**"):
            html_lines.append(
                f'<p style="font-weight:700;color:#e2e8f0;">{stripped[2:-2]}</p>'
            )
        else:
            html_lines.append(f'<p style="margin:8px 0;color:#cbd5e1;">{stripped}</p>')
    return "\n".join(html_lines)
